rootProject.name = 'flink-disk-operator'

include ':contract'
include ':disk-core'
include ':job'
include ':operator'
include ':mutator'
include ':mock-prometheus'
include ':keda-scaled-job'

dependencyResolutionManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            url "https://repository.apache.org/content/repositories/snapshots"
            mavenContent {
                snapshotsOnly()
            }
        }
    }
}
