rootLogger.level = INFO
rootLogger.appenderRef.console.ref = LogConsole
appender.console.name = LogConsole
appender.console.type = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
logger.sourcecoordinator.name = org.apache.flink.runtime.source.coordinator.SourceCoordinator
logger.sourcecoordinator.level = WARN
