apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flink-disk-scaledjob.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flink-disk-scaledjob.labels" . | nindent 4 }}
